trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 1

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build the code'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'your-azure-subscription-name'
    appName: 'your-azure-app-name'
    package: 'your-azure-app-package.zip'
